### ISSUE TITLE
thread 'main' panicked at 'attempt to multiply with overflow'

### ISSUE THREAD

**Issue by MuMiMaNz** [JonaC22/portfolio-cli#14]
Hello Jona , I tried to run your CLI with me ETH address and got this error
Loading ERC20 token transactions, this will take a while... (88/222)

thread 'main' panicked at 'attempt to multiply with overflow', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/num/mod.rs:668:5

I new to Rust and tried to study your works, Thanks for the good work 😄

**Comment by JonaC22** [comment]
Hi @MuMiMaNz ! sorry for the delayed reply, I had many things on-going.

Can you provide your ETH address? If possible, I don't want to violate your privacy and I understand, but that will lead me to reproduce the error. Also you can share me another ETH address that you might have found the same error.

Other viable option for debugging would be that you provide me the list of ECR20 tokens in your ETH wallet so I can find another similar ETH address and try to reproduce the bug.

Thank you!

**Comment by JonaC22** [comment]
@MuMiMaNz Maybe you can run again but with backtrace like this: `RUST_BACKTRACE=1 cargo run cargo run -- -a <eth-address> -v`
